services:
  nginx:
    image: nginx:opdi-bia
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/tls:/etc/nginx/ssl:ro
      - wordpress-data:/var/www/wordpress

  mariadb:
    image: mariadb:opdi-bia
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose: 
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  wordpress:
    image: wordpress:opdi-bia
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes :
      - wordpress-data:/var/www/wordpress

volumes:
  wordpress-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/opdi-bia/data/wordpress'

  mariadb-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/opdi-bia/data/mariadb'

networks:
  inception:
    driver: bridge
